# Generated by Django 3.0.8 on 2020-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indlist',
            name='imagee',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
