# Generated by Django 3.0.8 on 2020-07-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_indlist_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='indlist',
            name='encoded',
            field=models.TextField(default=''),
        ),
    ]
