# Generated by Django 3.0.8 on 2020-07-26 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0004_orgattendance_userattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
