# Generated by Django 3.0.8 on 2020-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0005_userattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='encoded',
            field=models.TextField(default=''),
        ),
    ]
