# Generated by Django 3.0.8 on 2020-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0006_userattendance_encoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='imagee',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
